config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("reservation/", include("reservations.urls", namespace="reservation")),
    path("users/", include("users.urls", namespace="users")),
]

# 개발 보드 settings 파일에 DEBUG Ture
# 이미지
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_veiw

# fbv
# urlpatterns = [path("", room_veiw.all_rooms, name="home")]
# cbv
app_name = "home"
urlpatterns = [path("", room_veiw.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"
# fbv
# urlpatterns = [path("<int:pk>", views.room_detail, name="detail")]
# cbv
# path("search", views.search, name="search"),
urlpatterns = [
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotoView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
    path("create/", views.CreateRoomView.as_view(), name="create"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github_login"),
    path("login/github/callback/", views.github_callback, name="github_callback"),
    path("login/kakao/", views.kakao_login, name="kakao_login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao_callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete_verification"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UserUpdateProfile.as_view(), name="update"),
    path("update-password/", views.UpdatePassword.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
]

templates/partials/footer.html
<footer class=" w-full mx-auto text-center py-10 border-t font-medium text-gray-500 ">
    &copy 2020 Airbnb, Inc. All rights reserved "Dont copy here plz "
</footer>

templates/partials/messages.html
{% if messages %}
<ul class="absolute mt-auto left-0 right-0 top-0  flex justify-center">
    {% for message in messages %}
    <li
        class="message mt-2 z-10 font-medium bg-gray-700 rounded-full text-white py-4 px-6 {% if message.tags %} {{ message.tags }}{% endif %}">
        {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-medium h-full">

    {% if user.is_authenticated %}
    <li class="nav_link">
        <a href="{% url 'users:switch-hosting' %}">
            {% if request.session.is_hosting %}
            Stop hosting
            {% else %}
            Start hosting
            {% endif %}
        </a>
    </li>
    {% if request.session.is_hosting %}
    <li class="nav_link"><a href="{% url 'rooms:create' %}">Create Room</a></li>
    {% endif %}
    <li class="nav_link"><a href="{{user.get_absolute_url}}">profile</a></li>
    <li class="nav_link"><a href="{% url "users:logout" %}">Log out</a></li>
    {% else %}
    <li class="nav_link"><a href="{% url "users:login" %}">Log in</a></li>
    <li class="nav_link"><a href="{% url "users:signup" %}">Sign up</a></li>
    {% endif %}

</ul>

templates/partials/social_login.html
<div class="flex flex-col container">
    <a href="{% url "users:github_login" %}" class="btn border border-gray-700 mb-2 font-bold text-gray-700">
        <i class="fab fa-github-alt mr-2 fa-lg"></i> Continue with Github
    </a>

    <a href="{% url "users:kakao_login" %}"
        class="btn border border-yellow-400 mb-2 font-bold text-yellow-800 bg-yellow-400">
        <i class="fas fa-comment mr-2 fa-lg"></i> Continue with Kakao
    </a>
</div>

<div class="flex items-center w-full">
    <div class="h-px w-full bg-gray-400 mx-2 my-8"></div>
    <span class=" text-gray-700 font-bold">or</span>
    <div class="h-px w-full bg-gray-400 mx-2 my-8"></div>
</div>