config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("reservation/", include("reservations.urls", namespace="reservation")),
    path("users/", include("users.urls", namespace="users")),
]

# 개발 보드 settings 파일에 DEBUG Ture
# 이미지
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_veiw

# fbv
# urlpatterns = [path("", room_veiw.all_rooms, name="home")]
# cbv
app_name = "home"
urlpatterns = [path("", room_veiw.HomeView.as_view(), name="home")]

reservations/urls.py
from django.urls import path
from . import views

app_name="reservations"

urlpatterns = [
    path("create/<int:room>/<int:year>-<int:month>-<int:day>", views.create, name="create"),
    path("<int:pk>", views.ReservationDetail.as_view(), name="detail")
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"
# fbv
# urlpatterns = [path("<int:pk>", views.room_detail, name="detail")]
# cbv
# path("search", views.search, name="search"),
urlpatterns = [
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotoView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
    path("create/", views.CreateRoomView.as_view(), name="create"),
]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):
    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    price = forms.IntegerField()
    room_type = forms.ModelChoiceField(
        empty_label="Any kind", queryset=models.RoomType.objects.all(), required=False
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    facilities = forms.ModelMultipleChoiceField(
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    # 해당 함수 호출은 view에서 form_valied함수에 의해 호출 됩니다.
    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator, EmptyPage
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.utils import timezone
from django.http import Http404
from django_countries import countries
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from users import mixins as user_mixins
from django.contrib.messages.views import SuccessMessageMixin

from . import models, forms
from math import ceil  # 올림하는 함수

# 페이지 랜더링 하는 fbv
def all_rooms(request):
    page = int(request.GET.get("page", 1))

    # 변수를 선언하고 all을 담으면 데이터 과부하가 되지 않는다 해당 변수를 사용할때 메모리에 올라간다.
    room_list = models.Room.objects.all()
    # model = models.Room
    paginator = Paginator(room_list, 10, orphans=5)
    # rooms = paginator.get_page(page) # 에러를 컨트롤 하고 싶지 않고 장고가 에러를 잡아주길 원하면 사용
    try:
        rooms = paginator.page(page)  # 페이지가 잘못 할당 되어 있을때 에러를 컨트롤 하고 싶다면 사용
        return render(request, "rooms/home.html", {"pages": rooms})
    except EmptyPage:
        return redirect("/")

    # rooms = paginator.page(1)

    # print(rooms.object_list)

    # 페이지 랜더링 가장 단순한 방법
    # page = request.GET.get("page", 1)
    # page = int(page or 1)
    # page_size = 10
    # limit = page_size * page
    # offset = limit - page_size
    # page_count = ceil(models.Room.objects.count() / page_size)
    # all_rooms = models.Room.objects.all()[offset:limit]
    # return render(
    #     request,
    #     "rooms/home.html",
    #     context={
    #         "rooms": all_rooms,
    #         "page": page,
    #         "page_count": page_count,
    #         "page_range": range(1, page_count + 1),
    #     },
    # )


# cbv
# https://ccbv.co.uk/ 사이트에서 cbv 속성 값을 볼수 있다. 여러개의 클래스로 있기 떄문에..
# 이처럼 선언을 하면 html에서 object list나 page_obj 이러한 변수를 사용할 수 있다 ex) room_list.html
# ListView를 상속 받았기 때문에 room_list,html을 찾는다.
class HomeView(ListView):

    """ HomeView Definition """

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # super()을 지우면 안된다.
        context["now"] = timezone.now()
        return context


# fbv
def room_detail(request, pk):
    # print("room_detail" end=""),print(pk)
    try:
        room = models.Room.objects.get(pk=pk)
    except models.Room.DoesNotExist:
        # 절대경로로 url 내보내기
        # return redirect("/")

        # 프로페션널 하게 리벌스 사용해서 namespace 찾아가기 자꾸 사용해서 손에 익히자
        # return redirect(reverse("core:home"))
        raise Http404()  # 404.html을 찾아가도록 만든다 꼭 템플릿 폴더 안에 있어여함

    return render(request, "rooms/detail.html", {"room": room})


# cbv
class RoomDetail(DetailView):

    """ RoomDetail Definition """

    model = models.Room


class SearchView(View):

    """ SearchView Definition """

    def get(self, request):

        country = request.GET.get("country")

        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():

                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = rooms = models.Room.objects.filter(**filter_args).order_by(
                    "-created"
                )

                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("pasge", 1)

                rooms = paginator.get_page(page)
                # print("Get으로 데이터 받는 형식, 검색조건 On")
                return render(
                    request, "rooms/searchform.html", {"form": form, "rooms": rooms}
                )
        else:
            form = forms.SearchForm()
            # print("빈폼으로 올때. 그냥 search페이지를 호출")

        return render(request, "rooms/searchform.html", {"form": form})


# def search(request):

# --------------------------------------------------------------------------------------

# search에서 form의 input에서준 city,country,room_type 값 받아오기
# city = request.GET.get("city", "Anywhere")
# city = str.capitalize(city)
# s_country = request.GET.get("country", "KR")
# room_type = int(request.GET.get("room_type", 0))
# price = int(request.GET.get("price", 0))
# guests = int(request.GET.get("guests", 0))
# bedrooms = int(request.GET.get("bedrooms", 0))
# beds = int(request.GET.get("beds", 0))
# baths = int(request.GET.get("baths", 0))
# instant = bool(request.GET.get("instant", False))
# superhost = bool(request.GET.get("superhost", False))
# s_amenities = request.GET.getlist("amenities")
# s_facilities = request.GET.getlist("facilities")
# # print(f"{s_amenities}, {s_facilities}")

# # 앞글자 대문자 만들기
# room_types = models.RoomType.objects.all()

# # ManyToMany 가져오는 방법 rooms/search.html을 참고 하면서 보시오!
# amenities = models.Amenity.objects.all()
# facilities = models.Facility.objects.all()
# # print(request.GET)

# form = {
#     "city": city,
#     "s_room_type": room_type,
#     "price": price,
#     "guests": guests,
#     "s_country": s_country,
#     "bedrooms": bedrooms,
#     "beds": beds,
#     "baths": baths,
#     "s_amenities": s_amenities,
#     "s_facilities": s_facilities,
#     "instant": instant,
#     "superhost": superhost,
# }
# choices = {
#     "countries": countries,
#     "room_types": room_types,
#     "amenities": amenities,
#     "facilities": facilities,
# }

# # Search 검색 조건 만들기
# # https://docs.djangoproject.com/en/3.0/ref/models/querysets/
# filter_args = {}
# if city != "Anywhere":
#     filter_args["city__startswith"] = city

# # 나라 조건
# filter_args["country"] = s_country

# # 방 타입 조건
# if room_type != 0:
#     filter_args["room_type__pk"] = room_type

# # 가격 조건
# if price != 0:
#     filter_args["price__lte"] = price

# # Guest 조건
# if guests != 0:
#     filter_args["guests__gte"] = guests

# # bedrooms 조건
# if bedrooms != 0:
#     filter_args["bedrooms__gte"] = bedrooms

# # beds 조건
# if beds != 0:
#     filter_args["beds__gte"] = beds

# # baths 조건
# if baths != 0:
#     filter_args["baths__gte"] = baths

# # instant 조건
# if instant is True:
#     filter_args["instant_book"] = True

# # superhost 조건
# if superhost is True:
#     filter_args["host__superhost"] = True

# # Amenitiy조건
# if len(s_amenities) > 0:
#     for s_amenitiy in s_amenities:
#         filter_args["amenities__pk"] = int(s_amenitiy)

# # Facilities 조건
# if len(s_facilities) > 0:
#     for s_facility in s_facilities:
#         filter_args["facilities__pk"] = int(s_facility)

# rooms = models.Room.objects.filter(**filter_args)
# print(bool(instant), bool(superhost))
# print(s_country)

# 개고생 하는 방법
# return render(request, "rooms/search.html", {**form, **choices, "rooms": rooms})


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    # get_object는 cbv에서 쓰인다 우리는 model에 던지는건 Room 정보이지 Room의 어느 객체인지 모른다.
    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotoView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    # print(f"Should delete {photo_pk} from {room_pk}")
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "사진을 지울 수 없습니다.")
        else:
            print(room_pk, user.pk)
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "사진 삭제 완료")

templates/rooms/detail.html
{% extends 'base.html' %}

{% block page_name %}home{% endblock page_name %}

{% block content %}

{% endblock content %}

templates/rooms/photo_create.html
{% extends 'base.html' %}

{% block page_name %}
Update Photo
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class=" container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-500">
    {% include 'mixins/room/room_form.html' with form=form cta="Update Photo" %}
</div>
{% endblock content %}

templates/rooms/photo_edit.html
{% extends 'base.html' %}

{% block page_name %}
Update Profile
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class=" container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-500">
    {% include 'mixins/room/room_form.html' with form=form cta="Update room" %}
</div>
{% endblock content %}

templates/rooms/room_create.html
{% extends 'base.html' %}

{% block page_name %}
Create Room
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class=" container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-500">
    {% include 'mixins/room/room_form.html' with form=form cta="Create room" %}
</div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends 'base.html' %}
{% load is_booked %}
{% block page_name %}Detail{% endblock page_name %}

{% block content %}
<div class=" container max-w-full h-75vh mb20 flex -mt-5">
    <div class=" h-full w-1/2 bg-cover " style="background-image: url({{room.first_photo}});">
    </div>
    <div class="h-full w-1/2 flex flex-wrap">
        {% for photo in room.get_next_four_photos  %}
        <div style="background-image: url({{photo.file.url}});"
            class=" w-1/2 h-auto bg-cover bg-center border border-gray-600">

        </div>
        {% endfor %}
    </div>
</div>

<div class=" container mx-auto flex justify-around pb-56">
    <div class=" w-1/2">
        <div class=" flex justify-between">
            <div class=" flex flex-col mt-10">
                <h4 class="text-3xl font-medium">{{room.name}}</h4>
                <span class=" text-gray-700 font-light">{{room.city}}</span>
            </div>
            <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center justify-center mt-10">
                {% include 'mixins/user_avatar.html' with user_obj=room.host %}
                <span class=" mt-4 text-gray-700">{{room.host.first_name}}</span>
            </a>
        </div>
        <div class="border-section flex  ">
            <span class="mr-5 font-light">{{room.room_type}}</span>
            <span class="mr-5 font-light">{{room.get_beds}}</span>
            <span class="mr-5 font-light">{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span>
            <span class="mr-5 font-light">{{room.baths}} bath{{room.baths|pluralize}}</span>
            <span class="mr-5 font-light">{{room.guests}} guest{{room.guests|pluralize}}</span>
        </div>
        <p class="border-section mt-8 pb-8  ">
            {{room.description}}
        </p>
        <div class="border-section">
            <h4 class=" font-normal text-lg mb-5">Amenities</h4>
            {% for a in room.amenities.all  %}
            <li class=" mb-2">{{a}}</li>
            {% endfor %}
        </div>
        <div class="border-section">
            <h4 class=" font-normal text-lg mb-5">Facilities</h4>
            {% for f in room.facilities.all  %}
            <li class=" mb-2">{{f}}</li>
            {% endfor %}
        </div>
        <div class="border-section">
            <h4 class=" font-normal text-lg mb-5">House_rules</h4>
            {% for h in room.house_rules.all  %}
            <li class=" mb-2">{{h}}</li>
            {% endfor %}
        </div>
        <div class="mt-5">
            <h4 class=" font-normal text-2xl mb-5">Reviews</h4>
            <div class=" flex items-center">
                <div>
                    <i class="fas fa-star text-teal-500"></i>
                    <span class=" font-bold text-xl">{{room.total_rating}} </span>
                </div>
                <div class=" h-5 w-xp bg-gray-400 mx-5"></div>
                <div>
                    <span class="font-bold text-xl">{{room.reviews.count}}</span>
                    <span class="">review{{room.reviews.count|pluralize}}</span>
                </div>
            </div>
            <div>
                {% for review in room.reviews.all  %}
                <div class="border-section">
                    <div class=" mb-3 flex">
                        <div>
                            {% include 'mixins/user_avatar.html' with user_obj=review.user h_and_w='w-10 h-10' text='text-lg' %}
                        </div>
                        <div class="flex flex-col ml-5">
                            <span class=" font-medium">{{review.user.first_name}}</span>
                            <span class=" text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                        </div>
                    </div>
                    <p>{{review}}</p>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
    <div class=" w-1/3">
        {% if room.host == user %}
        <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block mt-10">수정</a>
        {% else %}
        {% if not request.session.is_hosting %}

        {% for calendar in room.get_calendars %}
        <div class="mb-20">
            <span class=" text-content font-medium text-lg flex mb-8 mt-8 justify-center content-center">{{calendar.get_month}}/{{calendar.year}}</span>
            <div class="cal-grid mb-4 font-semibold">
                {% for day in calendar.day_name %}
                <span>{{day}}</span>
                {% endfor %}
            </div>
            <div class="cal-grid">
                {% for day in calendar.get_days  %}
                {% is_booked room day as is_booked_bool %}
                    {% if day.number != 0 %}
                    
                        {% if day.past %}
                            <span class=" rounded bg-gray-200 w-full text-center p1 text-gray-300">{{day}}</span>
                        {% elif is_booked_bool %}
                            <span class=" rounded bg-gray-200 w-full text-center p1 text-gray-300 line-through">{{day}}</span>
                        {% else %}
                            <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}" class=" bg-gray-200 text-center rounded text-gray-700 hover:bg-green-400 hover:text-white hover:font-medium cursor-pointer">{{day}}</a>
                        {% endif %}
                        
                    {% else %}
                        <span></span>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        {% endif %}
        {% endif %}

    </div>
</div>
{% endblock content %}

templates/rooms/room_edit.html
{% extends 'base.html' %}

{% block page_name %}
Update Photo
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class=" container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-500">
    {% include 'mixins/room/room_form.html' with form=form cta="Update Edit" %}
    <div class="mt-4 flex justify-center items-center">
        <a href="{% url 'rooms:photos' room.pk %}" class=" ml-4 text-teal-500 font-medium">Edit Photos</a>
    </div>
</div>
{% endblock content %}

templates/rooms/room_list.html
<!-- 참고 문서 -->
<!-- https://docs.djangoproject.com/en/3.0/ref/paginator/#django.core.paginator.Paginator -->

{% extends 'base.html' %}

{% block page_name %}home{% endblock page_name %}

{% block content %}

<div class="container mx-auto">

    <div class=" bg-gray-800 h-50vh mt-32 mb-12 -mx-40 rounded-xl bg-center bg-cover"
        style="background-image:url(https://images.unsplash.com/photo-1536315238512-4c8cebdaaf93?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop)">
    </div>

    <div class="flex flex-wrap -mx-40 mb-10">
        {% for room in object_list %}
        {% include 'mixins/room_card.html' with room=room %}
        {% endfor %}
    </div>
    <div class="flex items-center mx-auto container justify-center pb-10">
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500"><i class="fas fa-arrow-left fa-lg"></i>
        </a>
        {% endif %}

        {% for page_obj in page_range %}
        <a href="?page{{page}}">{{page}}</a>
        {% endfor %}

        <span class=" mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>

        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}" class=" text-teal-500"><i
                class="fas fa-arrow-right fa-lg"></i></a>
        {% endif %}
    </div>
    {% endblock content %}
</div>

templates/rooms/room_photos.html
{% extends 'base.html' %}

{% block page_name %}
Room Photos
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class=" container  mx-auto my-10 flex flex-col ">
    <div class="my-10 w-full">
        <a href="{% url 'rooms:add-photo' room.pk %}" class="btn-link w-1/6 block">Update Photo</a>
    </div>
    {% for photo in room.photos.all  %}
    <div class=" mb-5  border p-6 border-gray-500 flex justify-between">
        <div class=" flex items-start">
            <img src="{{photo.file.url}}" class=" w-32 h-32">
            <span class=" ml-5 text-lg">{{photo.caption}}</span>
        </div>
        <div class="flex flex-col w-1/5">
            <a class="btn-link w-full bg-teal-400" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Edit</a>
            <a class="btn-link w-full" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">Delete</a>
        </div>
    </div>
    {% endfor %}
    <div class=" flex justify-center items-center mt-4">
        <a href="{% url 'rooms:edit' room.pk %}" class=" font-medium text-xl text-teal-500">방 정보 수정</a>
    </div>
</div>
{% endblock content %}

templates/rooms/search.html
{% extends 'base.html' %}

{% block page_name %}
Search
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<h2>Search {{city}}</h2>
<form action="{% url "rooms:search" %}" method="GET">
    <div>
        <label for="city">City</label>
        <input type="text" id="city" name="city" placeholder="Search by City" value="{{city}}">
    </div>

    <div>
        <label for="country">Country</label>
        <select id="country" name="country">
            {% for country in countries %}
            <option value="{{country.code}}" {% if country.code == s_country %}selected{% endif %}>{{country.name}}
            </option>
            {% endfor %}
        </select>
    </div>

    <div>
        <label for="roomtype">Room Types</label>
        <select id="roomtype" name="room_type">
            <option value="0" {% if s_room_type == 0 %}selected{% endif %}>Any Kind</option>
            {% for type in room_types %}
            <option value="{{type.id}}" {% if s_room_type == type.pk %}selected{% endif %}>{{type}}</option>
            {% endfor %}
        </select>
    </div>

    <div>
        <label for="price">Price</label>
        <input value="{{price}}" type="number" id="price" name="price" placeholder="price">
    </div>
    <div>
        <label for="guests">Gusets</label>
        <input value="{{guests}}" type="number" id="guests" name="guests" placeholder="guests">
    </div>
    <div>
        <label for="bedrooms">Bedrooms</label>
        <input value="{{bedrooms}}" type="number" id="bedrooms" name="bedrooms" placeholder="bedrooms">
    </div>
    <div>
        <label for="beds">Beds</label>
        <input value="{{beds}}" type="number" id="beds" name="beds" placeholder="beds">
    </div>
    <div>
        <label for="baths">Baths</label>
        <input value="{{baths}}" type="number" id="baths" name="baths" placeholder="baths">
    </div>
    <div>
        <label for="instant">Instant Book Only?</label>
        <input type="checkbox" id="instant" name="instant" {% if instant %}checked{% endif %}>
    </div>
    <div>
        <label for="superhost">By Superhost Only?</label>
        <input type="checkbox" id="superhost" name="superhost" {% if superhost %}checked{% endif %}>
    </div>
    <div>
        <h3>Amenities</h3>
        <ul>
            {% for amenity in amenities %}
            <li>
                <label for="a_{{amenity.pk}}">{{amenity.name}}</label>
                <input type="checkbox" name="amenities" id="a_{{amenity.pk}}" value={{amenity.pk}}
                    {% if amenity.pk|slugify in s_amenities %}checked{% endif %}>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div>
        <h3>Facilities</h3>
        <ul>
            {% for facility in facilities %}
            <li>
                <label for="a_{{facility.pk}}">{{facility.name}}</label>
                <input type="checkbox" name="facilities" id="a_{{facility.pk}}" value={{facility.pk}}
                    {% if facility.pk|slugify in s_facilities %}checked{% endif %}>
            </li>
            {% endfor %}
        </ul>
    </div>
    <button>Search</button>
</form>

{% for room in rooms  %}
<h3>{{room}}</h3>
{% endfor %}

{% endblock content %}

templates/rooms/searchform.html
{% extends 'base.html' %}

{% block page_name %}
Search
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<h2>Search {{city}}</h2>
<form action="{% url "rooms:search" %}" method="GET">
    {{form.as_p}}
    <button>Search</button>
</form>

{% for room in rooms  %}
<h3>{{room}}</h3>
{% endfor %}

{% endblock content %}