config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("reservation/", include("reservations.urls", namespace="reservation")),
    path("users/", include("users.urls", namespace="users")),
]

# 개발 보드 settings 파일에 DEBUG Ture
# 이미지
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_veiw

# fbv
# urlpatterns = [path("", room_veiw.all_rooms, name="home")]
# cbv
app_name = "home"
urlpatterns = [path("", room_veiw.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"
# fbv
# urlpatterns = [path("<int:pk>", views.room_detail, name="detail")]
# cbv
# path("search", views.search, name="search"),
urlpatterns = [
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotoView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
    path("create/", views.CreateRoomView.as_view(), name="create"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="http://127.0.0.1:8000/static/css/styles.css"> -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <title>{% block page_name %}{% endblock page_name %} | Ubnb</title>
</head>

<body class="text-gray-800 mt-24 font-light">
    {% include 'partials/messages.html' %}
    <header
        class="container max-w-full flex items-center justify-between px-6 h-20 border-b border-gray-400 fixed bg-white top-0">
        <div class="flex items-center w-1/3">
            <a href="{% url "core:home" %}" class="mr-6">
                <img src="{% static 'img/django.png' %}" class="w-12">
            </a>
            {% block search-bar %}
            <form action="{% url "rooms:search" %}" method="GET" class="w-9/12">
                <input type="text" name="city" placeholder="어디로 여행 가세요?"
                    class="search-box border px-5 w-full font-medium text-gray-900 placeholder-gray-600 py-3 rounded-sm w-64 shadow-md hover:shadow-lg focus:outline-none">
            </form>
            {% endblock search-bar %}
        </div>
        {% include "partials/nav.html" %}
    </header>
    {% block content %} {% endblock content %}
    {% include "partials/footer.html" %}
</body>

</html>