config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("reservation/", include("reservations.urls", namespace="reservation")),
    path("users/", include("users.urls", namespace="users")),
]

# 개발 보드 settings 파일에 DEBUG Ture
# 이미지
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_veiw

# fbv
# urlpatterns = [path("", room_veiw.all_rooms, name="home")]
# cbv
app_name = "home"
urlpatterns = [path("", room_veiw.HomeView.as_view(), name="home")]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github_login"),
    path("login/github/callback/", views.github_callback, name="github_callback"),
    path("login/kakao/", views.kakao_login, name="kakao_login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao_callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete_verification"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UserUpdateProfile.as_view(), name="update"),
    path("update-password/", views.UpdatePassword.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
]

users/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.conf import settings
from django.utils.html import strip_tags
from django.template.loader import render_to_string
from django.shortcuts import reverse


class User(AbstractUser):
    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GEBDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OTHER, "Other"),
    )

    LANGUAGE_ENGLISH = "en"
    LANGUAGE_KOREA = "kr"

    LANGUAGE_CHOICES = (
        (LANGUAGE_ENGLISH, "English"),
        (LANGUAGE_KOREA, "Korea"),
    )

    LOGIN_EMAIL = "email"
    LOGIN_GITHUB = "github"
    LOGIN_KAKAO = "kakao"

    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_GITHUB, "Github"),
        (LOGIN_KAKAO, "Kakao"),
    )

    CURRENCY_USD = "usd"
    CURRENCY_KRW = "krw"

    CURRENCY_CHOICES = (
        (CURRENCY_USD, "USD"),
        (CURRENCY_KRW, "KRW"),
    )

    avatar = models.ImageField(upload_to="avatars", blank=True)
    gender = models.CharField(choices=GEBDER_CHOICES, max_length=10, blank=True)
    bio = models.TextField(default="", blank=True)
    birthdate = models.DateField(null=True, blank=True)
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=2, blank=True)
    currency = models.CharField(choices=CURRENCY_CHOICES, max_length=3, blank=True)
    superhost = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=120, default="")
    login_method = models.CharField(
        max_length=50, choices=LOGIN_CHOICES, default=LOGIN_EMAIL
    )

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                "Verify Airbnb Account",
                strip_tags(html_message),
                settings.EMAIL_FROM,
                [self.email],
                fail_silently=False,
                html_message=html_message,
            )
            self.save()  # fail)silenty는 에러가 보이냐 안보이냐 설정
        return

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        password = self.cleaned_data.get("password")
        email = self.cleaned_data.get("email")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data  # 비밀번호와 아이디가 맞았을 경우 clean data 리턴(아이디 비번)
            else:
                self.add_error("password", forms.ValidationError("비밀번호가 틀렸습니다."))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("유저가 없습니다."))


class SignUpForm(forms.ModelForm):
    # ModelForm은 내장된 save가 있어서 save를 따로 작성하지 않는다.
    # ModelForm은 model과 fields에 값을 넣어서 form을 표현한다.
    class Meta:
        model = models.User
        fields = ("first_name", "last_name", "email")
        # 필드로 선언한 폼 수정 작업 방법
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "Fist Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Nmae"}),
            "email": forms.TextInput(attrs={"placeholder": "Email"}),
        }

    # first_name = forms.CharField(max_length=80)
    # last_name = forms.CharField(max_length=80)
    # email = forms.EmailField()
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"}),
        label="Confirm Password",
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("이미 가입된 사용자가 있습니다.")
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password1")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("비밀번호를 재확인 바랍니다.")
        else:
            return password

    # def save(self):
    # first_name = self.cleaned_data.get("first_name")
    # last_name = self.cleaned_data.get("last_name")
    # email = self.cleaned_data.get("email")
    # password = self.cleaned_data.get("password")

    # user = models.User.objects.create_user(email, email, password)
    # user.first_name = first_name
    # user.last_name = last_name
    # user.save()
    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()  # 여기 세이브는 커밋 True로 만든다

users/views.py
import os
import requests

from django.shortcuts import render, redirect, reverse
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import FormView, DetailView, UpdateView
from django.urls import reverse_lazy
from django.core.files.base import ContentFile
from django.contrib import messages  # 메시지 실험
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin

from . import forms, models, mixins

# CSRF는 Cross Site Request Forgery
# 사이트 간 요청 위조

# mixin은 로그인 데코레이터 기능을 한다.
class LoginView(mixins.LoggedOutOnlyView, View):
    def get(self, request):
        form = forms.LoginForm(initial={"email": "test@google.com"})
        return render(request, "users/login.html", {"form": form})

    def post(self, request):
        form = forms.LoginForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)  # 로그인 인증 담기
            if user is not None:
                login(request, user)
                return redirect(reverse("core:home"))
        return render(request, "users/login.html", {"form": form})

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    messages.info(request, "안녕히 가세요.")
    logout(request)
    return redirect(reverse("core:home"))


class LoginViewEZ(FormView):
    template_name = "users/login.html"
    form_class = forms.LoginForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(
            self.request, username=email, password=password
        )  # 로그인 인증 담기
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


class SignUpView(FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(
            self.request, username=email, password=password
        )  # 로그인 인증 담기
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.save()
        # to do: add sucess message
    except models.User.DoesNotExist:
        # to do: add error message
        pass
    return redirect(reverse("core:home"))


def github_login(request):
    client_id = os.environ.get("GH_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_PW")
        code = request.GET.get("code", None)
        if code is not None:
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            tokenjson = token_request.json()
            error = tokenjson.get("error", None)
            if error is not None:
                raise GithubException("권한 코드를 찾을 수 없습니다.")
            else:
                access_token = tokenjson.get("access_token")
                profile_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                profile_json = profile_request.json()
                username = profile_json.get("login", None)
                if username is not None:
                    name = profile_json.get("name")
                    email = profile_json.get("email")
                    # print(profile_json)
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            raise GithubException(f"{user.login_method}으로 로그인 해주세요")

                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            email=email,
                            first_name=name,
                            username=email,
                            login_method=models.User.LOGIN_GITHUB,
                            email_verified=True,
                        )
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    messages.success(request, f"환영합니다. {user.first_name}")
                    return redirect(reverse("core:home"))
                    # if user is not None:
                    #     return redirect(reverse("users:login"))
                    # else:
                    #     models.User.objects.create(
                    #         first_name=name, email=email, bio=bio, username=email
                    #     )
                    #     login(request, user)
                    #     return redirect(reverse("core:home"))
                else:
                    raise GithubException("고객 정보를 얻을 수 없습니다.")
        else:
            raise GithubException("권한 코드를 얻을 수 없습니다.")
    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


# 카카오 로그인 연동
def kakao_login(request):
    app_key = os.environ.get("KAKAO_KEY")
    redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={app_key}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        app_key = os.environ.get("KAKAO_KEY")
        code = request.GET.get("code")
        redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={app_key}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        # print(token_json.json())
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("권한코드를 찾을 수 없습니다.")
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        # print(profile_request.json())
        profile_json = profile_request.json()
        email = profile_json.get("kakao_account").get("email")
        if email is None:
            raise KakaoException("이메일을 꼭 선택해 주세요.")
        nickname = profile_json.get("properties").get("nickname")
        profile_image = profile_json.get("properties").get(
            "profile_image"
        )  # 이미지 가져와서 avater에 추가
        try:
            user = models.User.objects.get(email=email)
            if user.login_method != models.User.LOGIN_KAKAO:
                raise KakaoException(f"{user.login_method}으로 로그인 해주세요")
        except models.User.DoesNotExist:
            user = models.User.objects.create(
                email=email,
                first_name=nickname,
                login_method=models.User.LOGIN_KAKAO,
                email_verified=True,
                username=email,
            )
            user.set_unusable_password()
            user.save()
            if profile_image is not None:
                print(profile_image)
                photo_request = requests.get(profile_image)  # byte 값으로 가져오기
                user.avatar.save(
                    f"{nickname}-avatar", ContentFile(photo_request.content)
                )  # bullshit파일을 django에서 처리하는 방법
        login(request, user)
        messages.success(request, f"환영합니다. {user.first_name}")
        return redirect(reverse("core:home"))
    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):

    model = models.User
    # UserProfileView가 뷰에서 찾았던 유저에 의해서 유저를 대체하고 있는데 이를 쓰면 해결된다.
    # 연결된 html에서 user와 user_obj를 쓸 수 있다.
    context_object_name = "user_obj"


# 성공시 메시지 SuccessMesageMixin
class UserUpdateProfile(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    # UpdateView는 url에 pk가 있으면 찾아 오지만 현재 플젝에는 pk가 url에 포함 되어 있지 않기 때문에 get_object함수를 사용한다.
    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "email",
        "first_name",
        "last_name",
        "gender",
        "bio",
        "language",
        "currency",
    )

    success_message = "개인정보 변경 완료"

    def get_object(self, queryset=None):
        return self.request.user

    # 저장을 누를 때 인터셉트 해서 가져올 수 있음.
    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        self.object.username = email
        self.object.save()
        return super().form_valid(form)

    def get_form(self, form_class=None):

templates/users/login.html
{% extends 'base.html' %}

{% block page_name %}
Login
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class=" container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-500">
    {% csrf_token %}
    {% include 'partials/social_login.html' %}
    {% include 'mixins/auth/auth_form.html' with form=form cta="Login" %}
    <!-- <form action="{% url "users:login" %}" method="post" class="w-full"> -->
    <!-- {{form.as_p}} -->
    <!-- {{form.email}} -->
    <!-- {{form.password}} -->

    <!-- {% for field in form  %} -->
    <!-- {% include 'mixins/auth/form_input.html' with field=field %} -->
    <!-- {% endfor %} -->


    <!-- <input type="text" placeholder="Email" class="focus:outline-none focus:border-teal-500">
        <input type="password" placeholder="Password" class="focus:outline-none focus:border-teal-500">  -->
    <!-- <button class="btn bg-red-500 text-white">Login</button> -->
    <!-- </form> -->
    <div class="mt-4 flex justify-center items-center">
        Don't have an account? <a href="{% url "users:signup" %}" class=" ml-4 text-teal-500 font-medium">Sign up</a>
    </div>
</div>
{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}

{% block page_name %}
Sign up
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class=" lg:w-5/12 md:w-1/2 xl:w-1/4 flex flex-col justify-center items-center mx-auto border p-10">
    {% include 'partials/social_login.html' %}
    {% include 'mixins/auth/auth_form.html' with form=form cta="Sign up" %}

    <div class="mt-4 flex justify-center items-center">
        Have an account? <a href="{% url "users:login" %}" class=" ml-4 text-teal-500 font-medium">Login</a>
    </div>
</div>
{% endblock content %}

templates/users/update-password.html
{% extends 'base.html' %}

{% block page_name %}
Update Password
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class=" container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-500">
    {% include 'mixins/auth/auth_form.html' with form=form cta="Change Password" %}
</div>
{% endblock content %}

templates/users/update-profile.html
{% extends 'base.html' %}

{% block page_name %}
Update Profile
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class=" container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-500">
    {% include 'mixins/auth/auth_form.html' with form=form cta="Update Profile" %}


    {% if object.login_method == "email" %}
    <div class="mt-4 flex justify-center items-center">
        <a href="{% url "users:password" %}" class=" ml-4 text-teal-500 font-medium">Change Password</a>
    </div>
    {% endif %}

</div>
{% endblock content %}

templates/users/user_detail.html
{% extends 'base.html' %}

{% block page_name %}
{{user_obj.first_name}}의 프로파일
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<!-- 바닥글이 밑으로 하는 기능 -->
<div class=" h-75vh">
    <div
        class=" container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-500">


        {% include 'mixins/user_avatar.html' with user_obj=user_obj %}

        <div class="flex items-center justify-center ">
            <span class="mt-1 text-3xl">{{user_obj.first_name}}</span>
            {% if user_obj.superhost %}
            <i class="fa fa-check-circle text-teal-400 ml-4"></i>
            {% endif %}
        </div>



        <span class=" text-lg">{{user_obj.bio}}</span>


        {% if user == user_obj %}
        <a href="{% url "users:update" %}" class="btn-link ">프로파일 수정</a>
        {% endif %}

    </div>

    <!-- 방개수가 없으면 보여주지 않기  -->
    {% if user_obj.rooms.count > 0 %}
    <div class="flex container mx-auto pb-10 flex-col items-center">
        <h3 class=" mb-12 text-xl">{{user_obj.first_name}}의 방</h3>
        <div class="flex flex-wrap -mx-40 mb-10">
            {% for room in user_obj.rooms.all %}
            {% include 'mixins/room_card.html' with room=room %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>

{% endblock content %}